### PR TITLE
Bring up to date with Inertia

### PR DESCRIPTION
**Pull request by sebastiandedeyne**
A few changes to bring everything up to date with Inertia.

- Renamed package
- Used new Inertia package named and added it as a peer dependency
- Changed Inertia import to named imports
- Changed default export to named export like the other adapters

### CODE REVIEW

**Comment by reinink** [comment]
We'll also need to update the readme.

**Comment by pedroborges** [comment]
I'll test it later today. Thanks @sebastiandedeyne!

**Comment by sebastiandedeyne** [comment]
Publish to npm is a question for @pedroborges. I have absolutely no idea how Svelte's build system deals with dependencies, so I can't say whether or not a bundler / transpiler needs to be introduced.

**Comment by reinink** [comment]
Keep us posted @pedroborges!

**Comment by pedroborges** [comment]
Svelte doesn't work with the bundled version of Inertia. I guess it's because all of its work is done in the compiler. It throws some "module not found" errors when trying to compile.

Screen Shot 2019-08-13 at 22 57 55

It works though when I set `src/index.js` to be the main file in `@inertiajs/inertia`. It also works when I import Inertia including the `src` directory like so `import { Inertia } from '@inertiajs/inertia/src'`.

I'm not sure what is the best way to handle it. Any ideas?

**Comment by pedroborges** [comment]
I'm getting an error on [this line](https://github.com/inertiajs/inertia/commit/b50230280c419aaa4b00d3b05638a596131a2542#diff-d2c945021d21eba7754a97605df4987dR163) on any page that uses the `Inertia.remember` method:

Screen Shot 2019-08-13 at 23 03 43

Reverting this section to the version prior to that commit works fine.

**Comment by sebastiandedeyne** [comment]
Do you have an example project online where I can tinker with this?

**Comment by pedroborges** [comment]
I tested on a client project. But I have a public repo with Inertia + Svelte. I have just updated it for you: https://github.com/pedroborges/laravel-svelte

It this repo, it doesn't throw the "modules not found" error. I'll test on my client project again.

If you go to the contact page you will see the other error related to `Inertia.remember`.

**Comment by sebastiandedeyne** [comment]
In your client project, what bundler are you using? If you're using rollup, you'll need to add the commonjs resolver plugin util we're able to add an mjs build to Inertia, which should be soon.

**Comment by pedroborges** [comment]
It's the exact same bundler as the public repo I shared with you. The only difference is that on my client's project I linked a local version of your PR. On the public repo, I added the package straight from Github.

**Comment by sebastiandedeyne** [comment]
Oh, in that case you might need to run `npm run build` in your local version first. The scripts that get distributed on npm are gitignored, so your bundler might be looking for files that don't exist.

Regarding the `remember` issue, that was a regression introduced in my PR, I published a new version that fixes it!

**Comment by rompetomp** [comment]
FWIW, I have the same issue as @pedroborges. I need to either run `npm install && npm run build` in `node_modules/@inertiajs/inertia`, or I can run `npm install` in `node_modules/@inertiajs/inertia-svelte`.
But it's not correct to be required to run a script inside node_modules.
 
I'm using webpack (encore) as my bundler.

**Comment by sebastiandedeyne** [comment]
> Shouldn't it be so that the dist folder is included in @inertiajs/inertia?

Yup, this issue will be solved once it's published to npm, which I think we can do once this is merged!

**Comment by pedroborges** [comment]
Thanks for all the help @sebastiandedeyne!

I'll update the readme and merge this later today.

**Pull request merged**
